export const importSvg = (icon) => {
  switch (icon) {
    case "image_1":
      return import("../../../assets/images/svg/image_1.svg");
    case "image_2":
      return import("../../../assets/images/svg/image_2.svg");
    case "image_3":
      return import("../../../assets/images/svg/image_3.svg");
    case "image_4":
      return import("../../../assets/images/svg/image_4.svg");
    case "image_5":
      return import("../../../assets/images/svg/image_5.svg");
    case "image_6":
      return import("../../../assets/images/svg/image_6.svg");
    case "image_7":
      return import("../../../assets/images/svg/image_7.svg");
    case "image_8":
      return import("../../../assets/images/svg/image_8.svg");
    case "image_9":
      return import("../../../assets/images/svg/image_9.svg");
    case "image_10":
      return import("../../../assets/images/svg/image_10.svg");
    case "image_11":
      return import("../../../assets/images/svg/image_11.svg");
    case "image_12":
      return import("../../../assets/images/svg/image_12.svg");
    case "image_13":
      return import("../../../assets/images/svg/image_13.svg");
    case "image_14":
      return import("../../../assets/images/svg/image_14.svg");
    case "image_15":
      return import("../../../assets/images/svg/image_15.svg");
    case "image_16":
      return import("../../../assets/images/svg/image_16.svg");
    case "image_17":
      return import("../../../assets/images/svg/image_17.svg");
    case "image_18":
      return import("../../../assets/images/svg/image_18.svg");
    case "image_19":
      return import("../../../assets/images/svg/image_19.svg");
    case "image_20":
      return import("../../../assets/images/svg/image_20.svg");
    case "image_21":
      return import("../../../assets/images/svg/image_21.svg");
    case "image_22":
      return import("../../../assets/images/svg/image_22.svg");
    case "image_23":
      return import("../../../assets/images/svg/image_23.svg");
    case "image_24":
      return import("../../../assets/images/svg/image_24.svg");
    case "image_25":
      return import("../../../assets/images/svg/image_25.svg");
    case "image_26":
      return import("../../../assets/images/svg/image_26.svg");
    case "image_27":
      return import("../../../assets/images/svg/image_27.svg");
    case "image_28":
      return import("../../../assets/images/svg/image_28.svg");
    case "image_29":
      return import("../../../assets/images/svg/image_29.svg");
    case "image_30":
      return import("../../../assets/images/svg/image_30.svg");
    case "image_31":
      return import("../../../assets/images/svg/image_31.svg");
    case "image_32":
      return import("../../../assets/images/svg/image_32.svg");
    case "image_33":
      return import("../../../assets/images/svg/image_33.svg");
    case "image_34":
      return import("../../../assets/images/svg/image_34.svg");
    case "image_35":
      return import("../../../assets/images/svg/image_35.svg");
    case "image_36":
      return import("../../../assets/images/svg/image_36.svg");
    case "image_37":
      return import("../../../assets/images/svg/image_37.svg");
    case "image_38":
      return import("../../../assets/images/svg/image_38.svg");
    case "image_39":
      return import("../../../assets/images/svg/image_39.svg");
    case "image_40":
      return import("../../../assets/images/svg/image_40.svg");
    case "image_41":
      return import("../../../assets/images/svg/image_41.svg");
    case "image_42":
      return import("../../../assets/images/svg/image_42.svg");
    case "image_43":
      return import("../../../assets/images/svg/image_43.svg");
    case "image_44":
      return import("../../../assets/images/svg/image_44.svg");
    case "image_45":
      return import("../../../assets/images/svg/image_45.svg");
    case "image_46":
      return import("../../../assets/images/svg/image_46.svg");
    case "image_47":
      return import("../../../assets/images/svg/image_47.svg");
    case "image_48":
      return import("../../../assets/images/svg/image_48.svg");
    case "image_49":
      return import("../../../assets/images/svg/image_49.svg");
    case "image_50":
      return import("../../../assets/images/svg/image_50.svg");
    default:
      return import("../../../assets/images/svg/image_1.svg");
  }
};