const activitiesList = [
  "Swimming",
  "Tennis",
  "Basketball",
  "Debate Competitions",
  "Red Cross",
  "Film Club",
  "Dance",
  "Hackathons",
  "Girl Scouts of the USA",
  "Science Honor Society",
  "English Honor Society",
  "Networking Clubs",
  "Computer Science Club",
  "Robotics Competitions",
  "Running Club",
  "Spanish Club",
  "French Club",
  "Asian Culture Club",
  "Entrepreneurship",
  "Yoga",
  "Coding/Programming",
  "Cooking Club",
  "Gardening",
  "Chess",
  "Creative Writing",
  "Photography Club",
  "Clean-up Campaigns",
  "Food Bank",
  "Animal Shelter",
  "Habitat for Humanity",
  "Science Olympiad",
  "Math Olympiad",
  "Environmental Club",
  "Robotics Club",
  "Music Club",
  "Computer Science Club",
  "Volunteer Tutoring",
  "Debate Club",
  "Math Club",
  "Art Club",
];
export default activitiesList;