const blogCategoryList = [
  "IT",
  "Technology",
  "E-commerce",
  "Career in Tech",
  "Tech News and Events",
  "Programming Languages",
  "Computer Science History",
  "Cryptography",
  "Science",
  "AR/VR",
  "Data Privacy",
  "Computer Graphics",
  "Artificial Intelligence",
  "Virtualization",
  "Cybersecurity",
  "Operating Systems",
  "Bioinformatics",
  "Data Structures",
  "Mobile Game",
  "Software Testing",
  "Ethical Hacking",
  "Cloud Security",
  "Bioinformatics Engineering",
  "Business Intelligence (BI)",
  "Network Security Engineer",
  "Full-stack Development",
  "Cloud Solutions Architect",
  "Software Architectering",
  "Data Analysist",
  "Robotics",
  "Artificial Intelligence Engineering",
  "Blockchain Technology",
  "Mobile App",
  "Systems Analyst",
  "Machine Learning",
  "Software Engineering",
  "Web Development",
  "Computer Network",
  "Graphic Degin",
  "Database",
  "Network",
  "Cloud Engineering",
];


export default blogCategoryList;