const universityList = [
  "Massachusetts Institute of Technology (MIT), United States",
  "University of Cambridge, United Kingdom",
  "University of Oxford, United Kingdom",
  "Harvard University, United States",
  "Stanford University, United States",
  "Imperial College London, United Kingdom",
  "ETH Zurich (Swiss Federal Institute of Technology), Switzerland",
  "National University of Singapore (NUS), Singapore",
  "UCL (University College London), United Kingdo",
  "University of California, Berkeley (UCB), United States",
  "University of Chicago, United State",
  "University of Pennsylvania, United States",
  "Cornell University, United State",
  "University of Melbourne,  Australi",
  "California Institute of Technology (Caltech), United States",
  "Yale University, United State",
  "Peking University, Mainland China",
  "Princeton University, United State",
  "University of New South Wales (UNSW Sydney), Australi",
  "University of Sydney, Australia",
  "University of Toronto, Canada",
  "University of Edinburg,hUnited Kingdom",
  "Columbia University, United States",
  "Universite PSL, France",
  "Tsinghua University,Mainland China",
  "Nanyang Technological University, Singapore (NTU), Singapore",
  "University of Hong Kong (UKU), Hong Kong SAR",
  "Johns Hopkins University, United States",
  "University of Tokyo, Japan ",
  "University of California, Los Angeles (UCLA), United States",
  "McGill University, Canada ",
  "University of Manchester, United Kingdom",
  "University of Michigan-Ann Arbor, United States",
  "Australian National University , Australia",
  "University of British Columbia, Canada",
  "Ecole Polytechnique Fédérale de Lausanne (EPFL) , Switzerland",
  "Technical University of Munich, Germany",
  "Institut Polytechnique de Paris, France",
  "New York University (NYU), United States",
  "King's College London, United Kingdom",
  "Seoul National University, South Korea",
  "Monash University, Australia",
  "University of Queensland, Australia",
  "Zhejiang University, Mainland China",
  "London School of Economics and Political Science (LSE), United Kingdom",
  "Kyoto University, Japan",
  "Delft University of Technology, Netherlands",
  "Northwestern University, United States",
  "Chinese University of Hong Kong (CUHK), Hong Kong SAR",
  "Fudan University, Mainland China",
  "Shanghai Jiao Tong University, Mainland China",
  "Carnegie Mellon University, United States",
  "University of Amsterdam, Netherlands",
  "Ludwig-Maximilians-Universität München, Germany",
  "University of Bristol, United Kingdom",
  "KAIST - Korea Advanced Institute of Science & Technology,South Korea",
  "Duke University, United States",
  "University of Texas at Austin, United States",
  "Sorbonne University, France",
  "Hong Kong University of Science and Technology (HKUST), Hong Kong SAR",
  "KU Leuven, Belgium",
  "University of California, San Diego (UCSD), United States",
  "University of Washington, United States",
  "University of Illinois at Urbana-Champaign, United States",
  "Hong Kong Polytechnic University, Hong Kong SAR",
  "Universiti Malaya (UM), Malaysia",
  "University of Warwick, United Kingdom",
  "University of Auckland, New Zealand",
  "National Taiwan University (NTU), Taiwan",
  "City University of Hong Kong, Hong Kong SAR",
  "Universite Paris-Saclay, France",
  "University of Western Australia, Australia",
  "Brown University, United States",
  "KTH Royal Institute of Technology, Sweden",
  "University of Leeds, United Kingdom",
  "University of Glasgow, United Kingdom",
  "Yonsei University, South Korea",
  "Durham University, United Kingdom",
  "Korea University, South Korea",
  "Osaka University, Japan",
  "Trinity College Dublin, The University of Dublin, Ireland",
  "University of Southampton, United Kingdom",
  "Pennsylvania State University, United States",
  "University of Birmingham, United Kingdom",
  "Lund University, Sweden",
  "Universidade de São Paulo, Brazil",
  "Lomonosov Moscow State University, Russia",
  "Universität Heidelberg, Germany",
  "The University of Adelaide, Australia",
  "University of Technology Sydney, Australia",
  "Tokyo Institute of Technology, Japan",
  "University of Zurich,  Switzerland",
  "Boston University, United States",
  "Universidad Nacional Autónoma de México (UNAM),  Mexico",
  "Universidad de Buenos Aires (UBA),  Argentina",
  "University of St Andrews,  United Kingdom",
  "Georgia Institute of Technology,  United States",
  "Freie Universitaet Berlin, Germany",
  "Purdue University, United States",
  "Pohang University of Science and Technology (POSTECH), South Korea",
  "University of Nottingham, United Kingdom",
];

export default universityList;
